# Generated by Django 4.2.7 on 2023-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=250)),
                ('originalIme', models.CharField(max_length=120)),
                ('zanr', models.CharField(max_length=200)),
                ('radnja', models.TextField(max_length=5000)),
                ('imdbOcena', models.CharField(max_length=100)),
                ('linkPreuzmi', models.CharField(max_length=1000)),
                ('linkGledaj', models.CharField(max_length=1000)),
                ('godina', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
