# Generated by Django 4.2.7 on 2023-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='originalIme',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
