# Generated by Django 4.2.7 on 2023-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0002_alter_film_image_alter_film_originalime'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='prevod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
