# Generated by Django 4.2.7 on 2023-11-30 13:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0004_rename_prevod_film_linkprevod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
