# Generated by Django 4.2.7 on 2023-11-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serija',
            old_name='ime',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='serija',
            old_name='originalIme',
            new_name='originalNaziv',
        ),
        migrations.RemoveField(
            model_name='serija',
            name='linkGledaj',
        ),
        migrations.RemoveField(
            model_name='serija',
            name='linkPreuzmi',
        ),
        migrations.RemoveField(
            model_name='serija',
            name='linkPrevod',
        ),
        migrations.CreateModel(
            name='Sezona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.IntegerField()),
                ('serija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sezone', to='serije.serija')),
            ],
        ),
        migrations.CreateModel(
            name='Epizoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.IntegerField()),
                ('linkPreuzmi', models.CharField(max_length=1000)),
                ('linkGledaj', models.CharField(max_length=1000)),
                ('linkPrevod', models.CharField(blank=True, max_length=200, null=True)),
                ('sezona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epizode', to='serije.sezona')),
            ],
        ),
    ]
